BASE_TASK_CONFIG_PATH: "configs/tasks/imagenav.yaml"
TRAINER_NAME: "ppo"
ENV_NAME: "NavRLEnv"
EXP_ID: "IMAGENAV-CURL-MAZE"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
VIDEO_OPTION: ["disk"]
TENSORBOARD_DIR: "tb"
VIDEO_DIR: "video_dir_imagenav_curl_maze"
TEST_EPISODE_COUNT: 10
EVAL_CKPT_PATH_DIR: "data/IMAGENAV-CURL-MAZE"
NUM_ENVIRONMENTS: 4
SENSORS: ["RGB_SENSOR"]
CHECKPOINT_FOLDER: "data/IMAGENAV-CURL-MAZE"
NUM_UPDATES: -1
TOTAL_NUM_STEPS: 9e6
LOG_INTERVAL: 25
NUM_CHECKPOINTS: 10

POLICY:
  name: "PointNavBaselinePolicy"


RL:
  PPO:
    # ppo params
    clip_param: 0.2
    ppo_epoch: 4
    num_mini_batch: 4
    value_loss_coef: 0.5
    entropy_coef: 0.01
    lr: 2.5e-4
    eps: 1e-5
    max_grad_norm: 0.5
    num_steps: 128
    hidden_size: 128
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: True
    use_linear_lr_decay: True
    reward_window_size: 50

